meta:
  environment: (( params "please set environment" ))
  stemcell: (( params "please set stemcell" ))

name: (( grab meta.environment ))

director_uuid: (( params "please set director_uuid" ))

releases: (( params "please set release" ))

jobs: (( params "please set jobs" ))

networks: (( params "please set networks" ))

properties: (( params "please set properties" ))

compilation:
  workers: 6
  network: ironic_cpi
  reuse_compilation_vms: true
  cloud_properties: (( params "please set compilation cloud properties" ))

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 30000-60000
  update_watch_time: 5000-60000
  serial: false

resource_pools:
  - name: small_z1
    network: ironic_cpi
    stemcell: (( grab meta.stemcell ))
    cloud_properties: (( params "please set resource_pool cloud properties" ))
